[package]
name = "clpi/iz"
version = "0.1.0-unstable.3"
description = "a cli utility someday, for now mostly just exploring zig + wasm"
license = "MIT"
readme = "README.md"
repository = "https://github.com/clpi/iz"

[[module]]
name = "iz"
source = "iz.wasm"
abi = "wasi"

# [module.interfaces]
# wasi = "0.0.0-unstable"

[[command]]
name = "iz"
module = "iz"
