[package]
name = "iz"
version = "0.1.0-alpha.1"
description = "a cli utility in zig"
license = "MIT"
repository = "https://github.com/clpi/iz"

[[module]]
name = "iz"
source = "zig-out/bin/iz.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

[[command]]
name = "iz"
module = "iz"
